[YDBTest#387] Fix go test failures on go 1.22 system as GO111MODULE=off is no longer supported
Background
----------
* See https://gitlab.com/YottaDB/DB/YDBTest/-/issues/387 and 5b1d284f commit message for more
  background on why GO111MODULE=off was a temporary workaround.

Issue
-----
Below is pasted from https://gitlab.com/YottaDB/DB/YDBTest/-/issues/387#note_1785585125

* Go 1.22 got released Feb 6 2024. And the release notes clearly indicate removing GO111MODULE=off support.

  https://tip.golang.org/doc/go1.22

  _go get is no longer supported outside of a module in the legacy GOPATH mode (that is, with GO111MODULE=off). Other build commands, such as go build and go test, will continue to work indefinitely for legacy GOPATH programs._

* On a system which has go 1.22 installed (an Ubuntu 20.04 system using go in a snap), I get the below
  error when running any test with the YDBGo wrapper.

  ```sh
  $ go version
  go version go1.22.0 linux/amd64

  $ go get -d -v -x -t lang.yottadb.com/go/yottadb
  14:44:58 : go: modules disabled by GO111MODULE=off; see 'go help modules'
  ```

* The distributions that YottaDB is currently supported on come installed with versions of go older
  than 1.22 and they still support GO111MODULE=off and so #387 is not critical but will very soon become
  a priority.

Round 1 of changes/fixes
------------------------
Below is pasted from https://gitlab.com/YottaDB/DB/YDBTest/-/issues/387#note_1790170510

* Below is a simple test demonstrating the issue.

  ```sh
  $ go version
  go version go1.22.0 linux/amd64

  $ go get -d -v -x -t lang.yottadb.com/go/yottadb
  go: go.mod file not found in current directory or any parent directory.
          'go get' is no longer supported outside a module.
          To build and install a command, use 'go install' with a version,
          like 'go install example.com/cmd@latest'
          For more information, see https://golang.org/doc/go-get-install-deprecation
          or run 'go help get' or 'go help install'.
  ```

* And then I ran the following command to create a simple `go.mod` file. And then the above `go get`
  command worked fine.

  ```sh
  $ echo "module gitlab.com/YottaDB/Lang/YDBGo" > go.mod

  $ go get -d -v -x -t lang.yottadb.com/go/yottadb
  # get https://proxy.golang.org/lang.yottadb.com/go/@v/list
  # get https://proxy.golang.org/lang.yottadb.com/@v/list
  # get https://proxy.golang.org/lang.yottadb.com/go/yottadb/@v/list
  # get https://proxy.golang.org/lang.yottadb.com/@v/list: 404 Not Found (0.267s)
  # get https://proxy.golang.org/lang.yottadb.com/go/@v/list: 404 Not Found (0.418s)
  # get https://proxy.golang.org/lang.yottadb.com/go/yottadb/@v/list: 200 OK (0.418s)
  # get https://proxy.golang.org/gopkg.in/yaml.v2/@v/list
  # get https://proxy.golang.org/github.com/pmezard/go-difflib/@v/list
  # get https://proxy.golang.org/github.com/stretchr/testify/@v/list
  # get https://proxy.golang.org/github.com/davecgh/go-spew/@v/list
  # get https://proxy.golang.org/github.com/pmezard/go-difflib/@v/list: 200 OK (0.026s)
  # get https://proxy.golang.org/gopkg.in/yaml.v2/@v/list: 200 OK (0.027s)
  # get https://proxy.golang.org/github.com/stretchr/testify/@v/list: 200 OK (0.034s)
  # get https://proxy.golang.org/github.com/davecgh/go-spew/@v/list: 200 OK (0.218s)
  go: added lang.yottadb.com/go/yottadb v1.2.2
  ```

* This addressed one part, the main part, of #387.

* The other part was that the `.git` directory was no longer being downloaded by `go get` under `go/src`
  subdirectory. This needs to be addressed as well in order to get the tests to work. But this is easily
  done using the following commands.

  ```sh
  mkdir -p go/src/lang.yottadb.com/go/yottadb
  git clone https://gitlab.com/YottaDB/Lang/YDBGo go/src/lang.yottadb.com/go/yottadb >& gitclone.log
  ```

* With both of the above changes, I was able to successfully run a `go` based subtest on a `go 1.22`
  system whereas previously it would reliably fail.

Note: All changes in the first round were to the file `com/setupgoenv.csh`.  Also, as part of a
review comment, it was mentioned that `go mod init` is a better way to create a `go.mod` file than
the `echo .,. > go.mod` command listed above so used that in the actual changes in this commit.

Round 2 of changes/fixes
------------------------
* With the first round of changes, I noticed that `go build` step in `com/imptp.csh` for `imptpgo.go`
  failed on various systems during testing when an imptp test randomly chose the YDBGo wrapper and
  the go version on that system was less than `go 1.22`. There were a few issues that I noticed.

* go build failed because it could not recognize the `imp.go` package (imported in `com/imptpgo.go`).
  Below was the actual symptom in `imptp.out`.

  ```
  imptpgo.go:17:2: package imp is not in GOROOT (/usr/lib/go-1.18/src/imp)
  TEST-E-FAILED : Unable to build imptpgo.go
  ```

  This is because `GO111MODULE=on` changes the way package imports work.

  The imptp go programs have been organized as `com/imp.go`, `com/imptpgo.go` and `com/impjobgo.go`
  since day one and 2 of them import the 3rd one and expect that to work.

  I did not want to spend time figuring a new layout and so took a look at the go 1.22 release notes.

  https://tip.golang.org/doc/go1.22

  _go get is no longer supported outside of a module in the legacy GOPATH mode (that is, with
  GO111MODULE=off). Other build commands, such as go build and go test, will continue to work
  indefinitely for legacy GOPATH programs._

  It mentioned that `GO111MODULE=off` is not supported for `go get` but is supported for `go build`
  and will continue to be so indefinitely.

  Therefore, I decided to set `GO111MODULE` env var to `on` for the `go get` stage but to `off` for
  the `go build` and `go get` stages.

* If YottaDB was built with ASAN enabled and was built with CLANG (not GCC), `go build` had a link
  problem on systems where the go version was `1.18.x`. Below was the actual symptom in `imptp.out`.

  ```
  /usr/bin/ld: dbg/libyottadb.so: undefined reference to `__asan_stack_free_7'
  /usr/bin/ld: dbg/libyottadb.so: undefined reference to `__asan_set_shadow_f5'
  .
  .
  /usr/bin/ld: dbg/libyottadb.so: undefined reference to `__asan_stack_malloc_9'
  /usr/bin/ld: dbg/libyottadb.so: undefined reference to `__asan_version_mismatch_check_v8'
  collect2: error: ld returned 1 exit status
  TEST-E-FAILED : Unable to build imptpgo.go
  ```

  In this case, `com/setupgoenv.csh` already had code which supplied `-ldflags 'fsanitize=address'` as
  parameters to the `go build` command. Not sure why this stopped working.

  But I noticed that for go 1.19 onwards, we instead supply a simpler `-asan` flag to the `go build`
  command. So I tried that with go 1.18 and that worked even though `man go build` did not list `-asan`
  as a supported option.

* If there was a test failure, the failure diff had lots of `Permission denied` messages.

  ```diff
  > gzip: */mupjnl_0/gtm5007/go/pkg/mod/lang.yottadb.com/go/yottadb@v1.2.2/doc.go.gz: Permission denied
  ```

  This is because the `go/pkg` sub-directory (which is now created by `go get` when `GO111MODULE=on`)
  has all sub-directories created with a `read-only` permission. That causes an error when the test
  framework tries to `gzip` all files in those subdirectories.

  This is fixed by enabling read-write permissions in all files under `go/pkg`.

* Note. All changes in the second round were to the file `com/setupgoenv.csh`.

Round 3 of changes/fixes
------------------------
* With the previous round of changes, the `go/unit_tests` subtest was the only test that continued
  to fail.

* It failed with the following diff.

  ```diff
  > TEST-E-FAILED : [go test -race -c -o unit_tests_exe lang.yottadb.com/go/yottadb] failed. go_test.log output follows.
  > # lang.yottadb.com/go/yottadb
  > buffer_t_array_test.go:18:2: cannot find package "github.com/stretchr/testify/assert" in any of:
  >       /snap/go/10506/src/github.com/stretchr/testify/assert (from $GOROOT)
  >       .*/go_0/unit_tests/go/src/github.com/stretchr/testify/assert (from $GOPATH)
  > FAIL  lang.yottadb.com/go/yottadb [setup failed]
  ```

* This is because `go/u_inref/unit_tests.csh` used the `GOPATH` scheme for `go test` whereas the `go get`
  was done with the `GOMODULE` scheme.

* To fix this, I enabled the `GOMODULE` approach by setting the `GO111MODULE` env var to `on`. And then ran
  the `go test` command. This did better but still failed with the following diff.

  ```
  > TEST-E-FAILED : [go test -race -c -o unit_tests_exe] failed. go_test.log output follows.
  > # lang.yottadb.com/go/yottadb
  > buffer_t_array_test.go:18:2: missing go.sum entry for module providing package github.com/stretchr/testify/assert (imported by lang.yottadb.com/go/yottadb); to add:
  >       go get -t lang.yottadb.com/go/yottadb
  > FAIL  lang.yottadb.com/go/yottadb [setup failed]
  ```

* As suggested, I enhanced `go/u_inref/unit_tests.csh` to do a `go get -t` and that let the test pass
  on all systems irrespective of whether they have `go 1.22` or older versions (e.g. `go 1.18`).

* All changes in the third round were to the file `go/u_inref/unit_tests.csh`.