[YDB#596] Fix rare triggers/ztriggercmd subtest failure due to DELIM/ZDELIM no longer needing commands=SET
* As part of a recent commit (a60cdd25), a specific trigger definition was moved from a failing section
  to a passing section as this trigger that used to fail in prior versions now works fine. Below is that
  trigger definition.

  ```sh
  +^zt("ZTR fail") -command=ZTR -xecute="do l^mrtn()" -delim="|" -name=ZTRDELIM
  ```

  This caused an occasional failure in the same subtest for a different reason.

  All subtests in the `triggers` test go through an `on-the-fly` trigger upgrade process where the
  triggers that got loaded are extracted from the journal file and they are reloaded using a randomly
  chosen older version and upgraded using MUPIP TRIGGER -UPGRADE to verify the trigger state is the same.
  But the loading using older version now fails if it encounters the specific previously-failing
  trigger definition (see `Error:` line below). And causes a test failure.

  ```sh
  $ tail -2 trig_input.trg
  "+^ztriggerloop2(lvn=1:129) -command=S,ZTR -xecute=""do ztriggerloop^ztriggercmd(lvn)"" -name=ztriggerloop2"
  "+^zt(""ZTR fail"") -command=ZTR "_$C(9)_" -xecute=""do l^mrtn()"" -delim=""|""          -name=ZTRDELIM"

  $ tail -3 60.trig_load
  Added SET and/or Non-SET trigger on ^ztriggerloop2 named ztriggerloop2
  Error: DELIM and ZDELIM need a commands=SET
  TRIGUPGRD_TEST-E-FAIL : Fail at trigger load operation. See triggers_1/ztriggercmd/1//60.trig_load
  ```

  This is now avoided by looking for this specific trigger definition and skipping it (by replacing it with
  a ';' definition) in the M program `trigLoadOldVer.m` (created by moving a lot of the code formerly
  in `trigupgrd_test.csh` into a new M program).