Fix various test failures due to [-Wimplicit-function-declaration] warning from gcc 14.2 (Ubuntu 24.10)
* After upgrading to Ubuntu 24.10, an in-house system failed various tests with the above warning.

* The full list of warnings and the various involved subtests are pasted below.

  ```sh
  $ cd errors_0/test_fao
  $ iconv -c compiler.out | grep '\-W'
  /usr/library/gtm_test/T999/errors/inref/test_fao.c:28:9: error: implicit declaration of function gtm_threadgbl_init [-Wimplicit-function-declaration]
  /usr/library/gtm_test/T999/errors/inref/test_fao.c:33:40: warning: format %lX expects argument of type long unsigned int, but argument 2 has type int * [-Wformat=]
  /usr/library/gtm_test/T999/errors/inref/test_fao.c:33:44: warning: format %lu expects argument of type long unsigned int, but argument 3 has type int * [-Wformat=]
  /usr/library/gtm_test/T999/errors/inref/test_fao.c:33:48: warning: format %ld expects argument of type long int, but argument 4 has type int * [-Wformat=]
  /usr/library/gtm_test/T999/errors/inref/test_fao.c:35:9: error: implicit declaration of function util_out_print [-Wimplicit-function-declaration]
  $ cd ../..

  $ cd xcall_0/basic
  $ iconv -c unicode_tests.log | grep '\-W'
  /usr/library/gtm_test/T999/xcall/inref/gtmxc_unistring.c:37:15: error: implicit declaration of function wcslen; did you mean xc_wcslen? [-Wimplicit-function-declaration]
  /usr/library/gtm_test/T999/xcall/inref/gtmxc_unistring.c:58:9: error: implicit declaration of function wcscat; did you mean xc_wcscat? [-Wimplicit-function-declaration]
  /usr/library/gtm_test/T999/xcall/inref/gtmxc_unistring.c:76:9: error: implicit declaration of function wcscpy; did you mean xc_wcscpy? [-Wimplicit-function-declaration]
  $ cd ../..

  $ cd encryption_0/error_messages
  $ iconv -c compilation.out | grep '\-W'
  /usr/library/gtm_test/T999/encryption/inref/corrupt_file.c:24:34: error: implicit declaration of function atoi [-Wimplicit-function-declaration]
  $ iconv -c modconfig.compil | grep '\-W'
  /usr/library/gtm_test/T998/com/modconfig.c:98:18: error: implicit declaration of function strcasecmp [-Wimplicit-function-declaration]
  $ cd ../..

  $ cd encryption_0/exp_test
  $ iconv -c compile.out | grep '\-W'
  passwd_external_call.c:13:9: error: implicit declaration of function snprintf [-Wimplicit-function-declaration]
  $ cd ../..
  ```

* Most of these warnings are fixed by including the appropriate header file (`<strings.h>` etc.).

* The `test_fao.c` warnings were fixed by explicitly adding prototypes of the missing functions since
  there was no header file in YDBTest that had those prototypes.

  Interestingly, I did see `-Wformat=` warnings too in test_fao.c but those disappeared once the
  `-Wimplicit-function-declaration` warnings were fixed.

* While fixing the `com/modconfig.c` warning, it was noticed that `com/modconfig.csh` deleted the
  compilation/link output (modconfig.compil or modconfig.link) even if the compile/link failed.
  This was fixed to not remove that output and also exit in that case with a non-zero status.

* The following additional cosmetic changes were done to satisfy the pre-commit hooks.
  - Copyrights were added to files that did not have any.
  - Files with wrong indentation were fixed by replacing spaces with tabs.