[OpenSUSE Tumbleweed] Fix imptp.csh test failures due to clang compiler and gcc linker
Background
----------
* On an in-house OpenSUSE Tumbleweed system, after a recent system patch, we saw various tests
  using `imptp.csh` fail when the test framework randomly picked `ydb_imptp_flavor` env var
  value of `1` (SimpleAPI) or `2` (SimpleThreadAPI).

* The linker map file from the failure has the following error.

  ```sh
  $ cat simpleapi_imptp.map
  .
  .
  /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: libyottadb.so: undefined reference to `__sanitizer_internal_memmove'
  /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: libyottadb.so: undefined reference to `__sanitizer_internal_memcpy'
  /usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: libyottadb.so: undefined reference to `__sanitizer_internal_memset'
  ```

Issue
-----
* In this case, the YottaDB build was done using CLANG and ASAN options randomly turned ON.

* But while compiling and linking `com/simpleapi_imptp.c`, the test system framework uses the
  `gt_cc_compiler` and `gt_ld_linker` env vars. Those in turn are hardcoded to `cc` in
  `YDB/sr_unix/gtm_env.csh` which points to `gcc` on the in-house system.

* This meant that the test system uses gcc for compiling and linking with libyottadb.so that has
  been linked by clang.

* I suspected that is the reason for the above error. It is generally not a good idea to use object
  files created by different toolchains while linking. I guess we have been lucky so far and finally
  it mattered with ASAN and a specific clang/gcc version.

* In the in-house system where the failure happened, below are the gcc/clang versions for the record.

  ```sh
  $ clang --version | head -1
  clang version 17.0.1

  $ gcc --version | head -1
  gcc (SUSE Linux) 13.2.1 20230912 [revision b96e66fd4ef3e36983969fb8cdd1956f551a074b]
  ```

Fix
---
* `com/gtmtest.csh` has been fixed to set the linker env vars to `clang` if we detect that
  libyottadb.so was built with `clang` (irrespective of whether ASAN was enabled or not). Even though
  the failure happened only when ASAN was turned ON, it is considered a good idea to keep the same
  linker in all cases so the change is done even for the ASAN=OFF case when libyottadb.so is built
  with `clang`.

  Note that we don't set `gt_cc_compiler` to point to `clang` in this case. The reason is mentioned
  in a comment in `com/gtmtest.csh`.

* With this change, it was verified that the failing test passes.