[PIPELINE] Fix build-imptp-rs job failure after Debian 13 docker upgrade
* The `build-imptp-rs` job started failing in the YDBTest pipeline recently with the
  following error.

  https://gitlab.com/YottaDB/DB/YDBTest/-/jobs/11103931128

  ```
  cargo:rerun-if-changed=Cargo.lock
  --- stderr
  error: unexpected argument '--whitelist-type' found
    tip: a similar argument exists: '--allowlist-type'
    tip: to pass '--whitelist-type' as a value, use '-- --whitelist-type'
  Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...
  For more information, try '--help'.
  thread 'main' panicked at /root/.cargo/git/checkouts/YDBRust-e0b609509240a648/79000ab/build.rs:84:23:
  error: failed to generate bindings with bindgen
  help: there may be more error output above
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

* This started happening after `yottadb/yottadb-debian:latest-master` docker image was
  updated to use Debian 13.

* We got similar failures in in-house testing on Debian 13 systems when imptp.csh tests
  randomly chose the YDBRust wrapper and tried to build `imptp.rs`. In that case, a
  workaround we found was to remove the `bindgen` package.

* I tried the same solution in the pipeline and that is to remove `bindgen` from line 37.

  **.gitlab-ci.yml**
  ```yaml
     37     - apt-get install -yq --no-install-recommends build-essential bindgen
     38     - cd com/imptp-rs; . $HOME/.cargo/env; cargo check --no-default-features
  ```

* But that ended up with the following different error.

  https://gitlab.com/nars1/YDBTest/-/jobs/11110511744

  ```
  error: failed to run bindgen: No such file or directory (os error 2)
  help: make sure `bindgen` is installed and in $PATH
  ```

* Therefore, instead tried removing `--no-default-features` from line 38 and that worked.

* Commit 0740b200 introduced the `build-imptp-rs` job and `cargo check` was invoked with
  `--no-default-features` right from the start.

* It is not clear to me why `--no-default-features` is needed and what it achieves. As
  removing this flag fixes the pipeline failure and avoids any changes to the YDBRust
  wrapper, I am going ahead with this solution for now.