Fix java/callouts subtest failure on ARMV6L due to different ArrayIndexOutOfBoundsException message
* The `ArrayIndexOutOfBoundsException` exception message used to show up as the following on older
  java versions.

  ```
  java.lang.ArrayIndexOutOfBoundsException: 3
  ```

* With Java 11.* versions on the `x86_64` architecture (came in as part of `Debian 10`), we noticed that
  the exception message became more descriptive. Below is the actual message in those later versions.

  ```
  java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
  ```

  Therefore, we enhanced `java/inref/com.test.ji.TestXC.java` to allow for both the above formats depending
  on the Java version (as part of commit 07c76f53ee51e82276e8c6ae904208964cb7cbc2).

* Recently we installed `Debian 11` on an in-house `ARMV6L` system. The Java version installed on this box
  was also a 11.* version (`11.0.11` to be exact). Therefore the test was expecting the more descriptive
  `ArrayIndexOutOfBoundsException` error message but the actual output was the older format message.
  Not clear exactly what the cause is. One thing we noticed was the VM in the below output on the ARMV6L system.

  ```
  $ java -version
  openjdk version "11.0.11" 2021-04-20
  OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1)
  OpenJDK Zero VM (build 11.0.11+9-post-Debian-1, interpreted mode)
  ```

  An x86_64 system with a similar java version had the following output instead.

  ```
  $ java -version
  openjdk version "11.0.11" 2021-04-20
  OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1)
  OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1, mixed mode, sharing)
  ```

  It is suspected that the `OpenJDK Zero VM` is the reason for the difference so the test script is now
  enhanced to check if that is the case and if so expect the older format output even though the Java
  version is 11 and above.