[YDB#734] Fix multi-host imptp test failures where local host YottaDB is not built with ASAN but remote host is
* In-house testing showed the following failure in a multi-host test that used imptp. On the remote side,
  imptp.csh would be invoked which tried to build a C version of the imptp application and failed
  during link time.

  ```diff
  --- switch_over/switch_over.diff ---
  70a71
  > TEST-E-MULTISITE replic action failed.Pls. check msr_execute_##FILTERED##NO.csh and all logs related to ##FILTERED## ##TIMESTAMP##
  96a98,102
  > remotehost:msreplic_E_1_4/switch_over/instance2/endtp.out
  > $ZSTATUS="150372994,wait+9^job,%YDB-E-GVUNDEF, Global variable undefined: ^%jobwait(0,""njobs"")"
  > $ZSTATUS="150372994,wait+9^job,%YDB-E-GVUNDEF, Global variable undefined: ^%jobwait(0,""njobs"")"
  > remotehost:msreplic_E_1_4/switch_over/instance2/imptp.out
  > LVNSET-E-LINKFAIL : Linking simpleapi_imptp failed. See simpleapi_imptp.map for details
  ```

  And the link map file had the following error.

  ```sh
  $ cat simpleapi_imptp.map
  .
  .
  /usr/bin/ld: libyottadb.so: undefined reference to `__asan_stack_free_7'
  .
  .
  ```

* This happens because `libyottadb.so` on the remote host was built with ASAN support but the local host
  was not built with ASAN support and therefore the remote host inherited the `gt_ld_options_common` env
  var from the local host which did not have the needed `-fsanitize=address` linker flags.

* This is fixed by moving the code in `com/gtmtest.csh` that set `gt_ld_options_common` (and a few other
  related env vars) to a new file `com/set_asan_other_env_vars.csh`.

  And this new file is now invoked from the following 2 files in the test framework which are usually
  invoked on the remote side by various tests.
  - com/imptp.csh
  - com/remote_getenv.csh