Fix java/callouts subtest failure on ARMV6L due to different ArrayIndexOutOfBoundsException message
Background
----------
* The `java/callouts` subtest failed on the ARMV6L with the following diff.

```
--- callouts/callouts.diff ---
11a12,15
> 8c8
> < %YDB-E-JNI, java.lang.ArrayIndexOutOfBoundsException: 3
> ---
> > %YDB-E-JNI, java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
```

* The `ArrayIndexOutOfBoundsException` exception message now shows up even on the ARMV6L as the following.

  ```
  java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
  ```

Issue
-----
* Commit 0a56cbe5 had made changes to allow for an alternate output on ARMV6L (see that commit message for
  details). The java version was 11 then but is now 17. Below is the current version.

  ```sh
  $ java -version
  openjdk version "17.0.9" 2023-10-17
  OpenJDK Runtime Environment (build 17.0.9+9-Debian-1deb12u1)
  OpenJDK Zero VM (build 17.0.9+9-Debian-1deb12u1, interpreted mode)
  ```

* It is still not clear exactly why the output was incorrect in version 11 but is correct in version 17
  only on the ARMV6L whereas it was correct in version 11 and 17 on x86_64 and AARCH64. The suspicion is
  that it is a `java` issue on the ARMV6L that was fixed in a later version.

Fix
---
* Therefore there is no need for commit 0a56cbe5 and the current commit reverts that and that is enough
  to let the java/callouts subtest pass again on ARMV6L.