Disable YDBPython random choice in com/imptp.csh if python3 version is 3.11.2
Background
----------
* On an in-house Ubuntu 23.04 system, we saw various tests that use `imptp.py` fail
  with one or more of the following symptoms.

  ```sh
  $ cat tcp_bkup_1_1/tcp_bkup/impjob_imptp0.mje1
  XXX lineno: 28, opcode: 151
  Traceback (most recent call last):
    File "tcp_bkup_1_1/tcp_bkup/impjob.py", line 468, in <module>
      yottadb.tp(tpfn_stage1, (parms,), tptype.decode("utf-8"), ("*",))
    File "tcp_bkup_1_1/tcp_bkup/python/.venv/lib/python3.11/site-packages/yottadb-1.0.0-py3.11-linux-x86_64.egg/yottadb/__init__.py", line 399, in tp
      return _yottadb.tp(callback, args, kwargs, transid, varnames)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  SystemError: unknown opcode
  ```

* Additionally, some test runs also encountered a SIG-11 in python code with the following stack trace.

  ```c
  (gdb) where
  #0  __pthread_kill_implementation (no_tid=0, signo=3, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
  #1  __pthread_kill_internal (signo=3, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
  #2  __GI___pthread_kill (threadid=<optimized out>, signo=3) at ./nptl/pthread_kill.c:89
  #3  gtm_dump_core () at sr_unix/gtm_dump_core.c:74
  #4  gtm_fork_n_core () at sr_unix/gtm_fork_n_core.c:163
  #5  generic_signal_handler (sig=11, info=0x7f5b9285df18 <stapi_signal_handler_oscontext+4424>, context=0x7f5b9285df98 <stapi_signal_handler_oscontext+4552>, is_os_signal_handler=1) at sr_unix/generic_signal_handler.c:492
  #6  ydb_os_signal_handler (sig=11, info=0x7fff7291f2f0, context=0x7fff7291f1c0) at sr_unix/ydb_os_signal_handler.c:85
  #7  <signal handler called>
  #8  _PyEval_EvalFrameDefault ()
  #9  _PyFunction_Vectorcall ()
  #10 ?? ()
  #11 ?? ()
  #12 ?? ()
  ```

Issue
-----
* Below is the version of `python3` on the Ubuntu 23.04 system.

  ```sh
  $ python3 --version
  Python 3.11.2
  ```

* And below is the version of `python3` on a Ubuntu 22.10 system where we have never seen such a failure.

  ```sh
  $ python3 --version
  Python 3.10.7
  ```

* Therefore the python3 version bump from 3.10.7 to 3.11.2, as part of the Ubuntu 23.04 upgrade,
  seems to be the reason for the test failures.

Fix
---
* I decided to disable the YDBPython wrapper random choice in `com/imptp.csh` if the `python3` version is
  `3.11.2`. I am hoping the next `python3` version will fix this issue.