[YDB#734] Fix r120/miximage and r124/ydb401 subtest failures when run with CLANG + ASAN
* When tests were run with a build of YottaDB that was done using CLANG and ASAN, both the
  subtests mentioned in the commit message title failed with linker errors like the following.

  ```
  /usr/bin/ld: libyottadb.so: undefined reference to `__asan_stack_free_7'
  ```

* The issue is that since ASAN is linked statically when used with CLANG, one needs to specify
  `-fsanitize=address` at link time of the main executable that is going to later open
  libyottadb.so (which was built with `-fsanitize=address`).

* This additional linker flag is already available through the `$gt_ld_options_common` env var.
  So this commit just adds this env var to the linker command.