Fixed r200/ydbpython32 and r136/ydb935 subtests failures on Ubuntu 24.04
Failures in the r200/ydbpython32 and r136/ydb935 subtests were reported on Ubuntu 24.04 due to the following error:

```python
NotImplementedError: Support for egg-based install has been removed.
```

This is due to the deprecation of the `.egg` binary format used for Python module installs, per the [Python packaging documentation](https://packaging.python.org/en/latest/discussions/package-formats/#what-about-eggs):

> "Egg" is an old package format that has been replaced with the wheel format. It should not be used anymore. Since August 2023, PyPI rejects egg uploads.

The fix is to use the new wheel format instead of the deprecated `.egg` format by replacing calls to `python setup.py install` with `python -m pip install .`.