[YDB#734] [#412] Re-enable go tests even for CLANG + ASAN (completely reverts 003a4d9d)
Background
----------
Below is pasted from https://gitlab.com/YottaDB/DB/YDBTest/-/merge_requests/2053#note_2651948427

* While analyzing a different failure today on SUSE and RHEL systems, I noticed it had the same symptom
  as mentioned at https://gitlab.com/YottaDB/DB/YDBTest/-/merge_requests/2053#note_2043556763.

  ```
  /usr/bin/ld: /usr/library/V998_R201/dbg/libyottadb.so: undefined reference to '__sanitizer_internal_memmove'
  ```

* And today's failure too was when YottaDB was built with CLANG + ASAN.

* So tried out `env CC=clang` like mentioned in that same comment and reran the CLANG + ASAN test on
  SUSE and RHEL. SUSE and RHEL 8 passed the test but RHEL 9 continued to fail. This time though with a
  different symptom.

  ```
  /opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../bin/ld: /usr/lib64/libctf.so.0: version 'LIBCTF_1.1' not found (required by /opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/../../../../bin/ld)
  ```

* Just like previously mentioned at https://gitlab.com/YottaDB/DB/YDBTest/-/merge_requests/2053#note_2043556763.

* Last time I did not spend a lot of time on it. This time though I took a look at it. And
  found the issue. It is the `LD_LIBRARY_PATH` env var that gets set in the test framework (by
  `com/set_ldlibpath.csh`). Unsetting this env var let the test pass fine even on RHEL 9. So I
  am going to make this change in a new MR as this means we can now run CLANG + ASAN tests on all
  distributions with no exceptions.

Fix
---
* The primary fix is to `com/setupgoenv.csh` to set the `CC` env var to `clang` if it is detected to
  be a CLANG + ASAN build. This fixes the `undefined reference to __sanitize_internal_memcpy` errors.

* The secondary fix is to ensure the `LD_LIBRARY_PATH` env var is not set in such cases (to avoid the
  `LIBCTF_1.1` error mentioned above).

  Instead of the unsetting the `LD_LIBRARY_PATH` env var (that gets set in `com/set_ldlibpath.csh`)
  in just the failing subtest, I thought of removing the framework level set of this env var in
  `com/set_ldlibpath.csh` to see what if any fallout is. And there was NO fallout. So went ahead with
  this change as that is a better change.

* And because of the primary fix, code that excluded any go related testing for CLANG + ASAN was all
  re-enabled as part of this commit.

  Note that commit 003a4d9d first disabled go tests if CLANG + ASAN.

  And later commit 6e83ed6a re-enabled some of them (i.e. reverted 003a4d9d partially).

  The current commit re-enables ALL go tests for CLANG + ASAN (i.e. reverts 003a4d9d completely).

  And because of this, the env var `ydb_test_gover_lt_118_or_rhel` was no longer needed and instead
  all such usages can be changed to `ydb_test_gover_lt_118` (as the rhel case now had go tests enabled).
  But then I realized that all YottaDB supported distributions have go 1.19 or so (on both x86_64 and
  aarch64) and so I figured that even `ydb_test_gover_lt_118` is no longer needed.  So all code that
  used either of these two env vars was removed as part of this commit.

* This additionally meant that there was no reason for the `set_ldlibpath.csh` script as its only
  purpose was to set the `LD_LIBRARY_PATH` env var (and the `LIBPATH` env var). Therefore removed it
  altogether and removed its reference from all callers of this script.

* Additionally, a few scripts in the test system assumed that `LIBPATH` and `LD_LIBRARY_PATH` env vars
  were always set. But that is no longer guaranteed because of the removal of `set_ldlibpath.csh` calls.
  And so the assuming scripts were modified to check if these env vars were set and if not do nothing. The
  following scripts had these changes
  - com/set_encrypt_env.csh
  - encryption/u_inref/gtmpasswd.csh
  - java/instream.csh

* And finally, the following scripts were changed to reformat `subtest_list_non_replic` usages to
  conform to the pre-commit hook format (one subtest in one line).
  - r128/instream.csh
  - r134/instream.csh